site_name: Hardware All The Things
site_description: 'Hardware/IOT Pentesting Wiki'
site_url: https://swisskyrepo.github.io/HardwareAllTheThings

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - navigation.tracking
    - navigation.top

extra_css:
    - custom.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/swisskyrepo/HardwareAllTheThings/
edit_uri: edit/master/
plugins:
  - search
  - git-revision-date-localized
  - social

# - meta-descriptions
# insiders-2.12.0 ·  Plugin ·  Experimental
# - social
# - tags
# - toc.integrate
# - navigation.instant
# logo: 'images/site_logo.png'
# favicon: 'images/favicon.png'